import { db } from "@workspace/db";
import { detectionsTable, incidentsTable, agentsTable } from "@workspace/db";

async function seedDetectionsAndIncidents() {
  console.log("Seeding detections and incidents...");

  const agents = await db.select().from(agentsTable);
  const secAgent = agents.find(a => a.role === "security_lead");
  const redAgent = agents.find(a => a.role === "red_team");
  const engAgent = agents.find(a => a.role === "senior_engineer");

  await db.insert(detectionsTable).values([
    {
      name: "Sigma: Credential Dumping via LSASS",
      description: "Detects access to LSASS memory to extract credentials using tools like Mimikatz or ProcDump.",
      type: "sigma",
      ruleContent: `title: Credential Dumping via LSASS Access\nstatus: stable\nlogsource:\n  category: process_access\n  product: windows\ndetection:\n  selection:\n    TargetImage|endswith: '\\lsass.exe'\n    GrantedAccess|contains:\n      - '0x1010'\n      - '0x1410'\n  condition: selection\nlevel: critical\ntags:\n  - attack.credential_access\n  - attack.t1003.001`,
      severity: "critical",
      status: "active",
      mitreTechnique: "T1003.001",
      mitreTactic: "Credential Access",
      tags: "credential_dumping,lsass,mimikatz",
      author: "SEC-1",
      falsePositiveRate: "2",
      truePositiveCount: "47",
    },
    {
      name: "YARA: Ransomware File Encryption Signature",
      description: "Detects common ransomware file encryption patterns and ransom note creation behavior.",
      type: "yara",
      ruleContent: `rule Ransomware_Generic {\n  meta:\n    description = "Detects generic ransomware behavior"\n    severity = "critical"\n  strings:\n    $ransom1 = "YOUR FILES HAVE BEEN ENCRYPTED" nocase\n    $ransom2 = "bitcoin" nocase\n    $ext1 = ".locked" nocase\n    $ext2 = ".encrypted" nocase\n    $enc_func = { 48 8B 4D ?? 48 8B 55 ?? E8 ?? ?? ?? ?? }\n  condition:\n    any of ($ransom*) and any of ($ext*) or $enc_func\n}`,
      severity: "critical",
      status: "active",
      mitreTechnique: "T1486",
      mitreTactic: "Impact",
      tags: "ransomware,encryption,impact",
      author: "SEC-1",
      falsePositiveRate: "1",
      truePositiveCount: "12",
    },
    {
      name: "Sigma: PowerShell Encoded Command Execution",
      description: "Detects suspicious PowerShell execution with encoded command parameter — commonly used in fileless attacks.",
      type: "sigma",
      ruleContent: `title: PowerShell Encoded Command\nstatus: stable\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith: '\\powershell.exe'\n    CommandLine|contains:\n      - ' -enc '\n      - ' -EncodedCommand '\n      - ' -e JAB'\n  condition: selection\nlevel: high\ntags:\n  - attack.execution\n  - attack.t1059.001`,
      severity: "high",
      status: "active",
      mitreTechnique: "T1059.001",
      mitreTactic: "Execution",
      tags: "powershell,execution,fileless",
      author: "ENG-1",
      falsePositiveRate: "8",
      truePositiveCount: "203",
    },
    {
      name: "Behavioral: Unusual Admin Account Creation",
      description: "Detects creation of admin accounts outside of change windows or by non-privileged processes — indicative of persistence establishment.",
      type: "behavioral",
      ruleContent: `detection_logic:\n  event_type: user_creation\n  conditions:\n    - field: privileges\n      operator: contains\n      value: "Administrator"\n    - field: time_of_day\n      operator: outside\n      value: "08:00-18:00"\n    - field: parent_process\n      operator: not_in\n      value: ["mmc.exe", "lusrmgr.msc"]\n  threshold: 1\n  window: 5m`,
      severity: "high",
      status: "active",
      mitreTechnique: "T1136.001",
      mitreTactic: "Persistence",
      tags: "persistence,account_creation,privilege_escalation",
      author: "SEC-1",
      falsePositiveRate: "3",
      truePositiveCount: "28",
    },
    {
      name: "IOC: Known C2 Infrastructure — Cobalt Strike Beacons",
      description: "Matches known Cobalt Strike C2 server IP ranges and domain patterns from threat intelligence feeds.",
      type: "ioc",
      ruleContent: `ioc_type: network\nindicators:\n  ips:\n    - 185.220.101.0/24\n    - 194.165.16.0/24\n    - 45.142.212.0/24\n  domains:\n    - "*.cloudflare-analytics[.]com"\n    - "cdn-updates[.]net"\n    - "secure-cdn-dl[.]com"\n  patterns:\n    - uri: "/updates/beacon"\n    - user_agent: "Mozilla/5.0 (compatible; MSIE 9.0)"\nseverity: critical\nconfidence: 95`,
      severity: "critical",
      status: "active",
      mitreTechnique: "T1071.001",
      mitreTactic: "Command and Control",
      tags: "c2,cobalt_strike,network",
      author: "RT-1",
      falsePositiveRate: "1",
      truePositiveCount: "8",
    },
    {
      name: "Sigma: Lateral Movement via PsExec",
      description: "Detects remote execution via PsExec — a common lateral movement technique used by attackers and red teams.",
      type: "sigma",
      ruleContent: `title: PsExec Lateral Movement\nstatus: stable\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith:\n      - '\\psexec.exe'\n      - '\\psexec64.exe'\n    CommandLine|contains:\n      - ' \\\\\\\\'\n  condition: selection\nlevel: high\ntags:\n  - attack.lateral_movement\n  - attack.t1021.002`,
      severity: "high",
      status: "testing",
      mitreTechnique: "T1021.002",
      mitreTactic: "Lateral Movement",
      tags: "lateral_movement,psexec,smb",
      author: "RT-1",
      falsePositiveRate: "12",
      truePositiveCount: "34",
    },
    {
      name: "YARA: Webshell Detection — PHP/ASP",
      description: "Detects web shell deployment in PHP and ASP environments using known patterns and eval/exec signatures.",
      type: "yara",
      ruleContent: `rule Webshell_Generic {\n  meta:\n    description = "Detects PHP/ASP webshells"\n    severity = "high"\n  strings:\n    $php1 = "<?php" nocase\n    $eval = /eval\\s*\\(\\s*(base64_decode|gzinflate|str_rot13)/ nocase\n    $exec = /system\\s*\\(\\s*\\$_(GET|POST|REQUEST)/ nocase\n    $asp1 = "<%"\n    $asp_exec = /Execute\\s*\\(\\s*Request/ nocase\n  condition:\n    ($php1 and ($eval or $exec)) or\n    ($asp1 and $asp_exec)\n}`,
      severity: "high",
      status: "active",
      mitreTechnique: "T1505.003",
      mitreTactic: "Persistence",
      tags: "webshell,persistence,php,asp",
      author: "SEC-1",
      falsePositiveRate: "4",
      truePositiveCount: "19",
    },
    {
      name: "Behavioral: Data Exfiltration via DNS Tunneling",
      description: "Detects anomalous DNS query volume and entropy patterns indicative of DNS tunneling for data exfiltration.",
      type: "behavioral",
      ruleContent: `detection_logic:\n  event_type: dns_query\n  conditions:\n    - field: query_length\n      operator: greater_than\n      value: 100\n    - field: subdomain_entropy\n      operator: greater_than\n      value: 3.8\n    - field: queries_per_minute\n      operator: greater_than\n      value: 50\n  threshold: 3\n  window: 10m\n  group_by: source_ip`,
      severity: "medium",
      status: "active",
      mitreTechnique: "T1048.003",
      mitreTactic: "Exfiltration",
      tags: "dns_tunneling,exfiltration,network",
      author: "SEC-1",
      falsePositiveRate: "6",
      truePositiveCount: "11",
    },
    {
      name: "Sigma: Suspicious Registry Persistence",
      description: "Detects registry run key modifications commonly used by malware for persistence establishment.",
      type: "sigma",
      ruleContent: `title: Registry Run Key Persistence\nstatus: stable\nlogsource:\n  category: registry_set\n  product: windows\ndetection:\n  selection:\n    TargetObject|contains:\n      - '\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run'\n      - '\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce'\n    Details|contains:\n      - '.exe'\n      - '.ps1'\n      - '.vbs'\n  condition: selection\nlevel: medium\ntags:\n  - attack.persistence\n  - attack.t1547.001`,
      severity: "medium",
      status: "active",
      mitreTechnique: "T1547.001",
      mitreTactic: "Persistence",
      tags: "registry,persistence,run_keys",
      author: "ENG-1",
      falsePositiveRate: "15",
      truePositiveCount: "67",
    },
    {
      name: "IOC: Phishing Domain — Lookalike Detection",
      description: "Detects access to lookalike domains using typosquatting and homoglyph techniques targeting company assets.",
      type: "ioc",
      ruleContent: `ioc_type: domain\ndetection_method: lookalike_analysis\nlegitimate_domains:\n  - rapidforce.io\n  - internal-auth.rapidforce.io\npatterns:\n  - type: typosquatting\n    examples:\n      - rapidf0rce.io\n      - rapid-force.io\n      - rapldforce.io\n  - type: homoglyph\n    examples:\n      - rаpidforce.io  # Cyrillic 'а'\n  - type: subdomain_abuse\n    pattern: "rapidforce.io.*\\.com"\nseverity: medium\nconfidence: 78`,
      severity: "medium",
      status: "active",
      mitreTechnique: "T1566.002",
      mitreTactic: "Initial Access",
      tags: "phishing,lookalike,domain",
      author: "SEC-1",
      falsePositiveRate: "5",
      truePositiveCount: "23",
    },
    {
      name: "Behavioral: Privileged Container Escape Attempt",
      description: "Detects patterns consistent with container escape attempts — privileged container usage, cgroup exploitation, namespace breakout.",
      type: "behavioral",
      ruleContent: `detection_logic:\n  event_type: container_activity\n  conditions:\n    - field: privileged\n      operator: equals\n      value: true\n    - field: capability\n      operator: contains\n      value: "CAP_SYS_ADMIN"\n    - field: syscall\n      operator: in\n      value: ["unshare", "clone", "mount"]\n  threshold: 2\n  window: 60s`,
      severity: "high",
      status: "testing",
      mitreTechnique: "T1611",
      mitreTactic: "Privilege Escalation",
      tags: "container,privilege_escalation,kubernetes",
      author: "DEVOPS-1",
      falsePositiveRate: "7",
      truePositiveCount: "5",
    },
    {
      name: "Sigma: Pass-the-Hash Attack Detection",
      description: "Detects NTLM authentication with mismatched Logon Type 3 patterns consistent with pass-the-hash attacks.",
      type: "sigma",
      ruleContent: `title: Pass the Hash Attack\nstatus: experimental\nlogsource:\n  product: windows\n  service: security\ndetection:\n  selection:\n    EventID: 4624\n    LogonType: 3\n    LogonProcessName: NtLmSsp\n    WorkstationName: ''\n  filter:\n    AccountName|endswith: '$'\n  condition: selection and not filter\nlevel: high\ntags:\n  - attack.lateral_movement\n  - attack.t1550.002`,
      severity: "high",
      status: "review",
      mitreTechnique: "T1550.002",
      mitreTactic: "Defense Evasion",
      tags: "pass_the_hash,ntlm,lateral_movement",
      author: "RT-1",
      falsePositiveRate: "18",
      truePositiveCount: "14",
    },
  ]);

  console.log("Detections seeded.");

  await db.insert(incidentsTable).values([
    {
      title: "Active Ransomware Deployment — Production Cluster",
      description: "Multiple production nodes showing file encryption activity consistent with LockBit 3.0 ransomware. Automated containment initiated. 3 nodes isolated. Data backup integrity confirmed.",
      severity: "critical",
      status: "investigating",
      type: "ransomware",
      assignedAgentId: secAgent?.id,
      affectedSystems: "prod-node-01, prod-node-02, prod-node-03, storage-cluster-a",
      iocIndicators: "185.220.101.47, lockbit-payment[.]onion, .lockbit3 extension",
      playbookSteps: "1. Isolate affected nodes\n2. Preserve forensic images\n3. Verify backup integrity\n4. Identify patient zero\n5. Eradicate ransomware\n6. Restore from clean backups\n7. Conduct post-incident review",
      attackVector: "Phishing email → macro execution → lateral movement via RDP",
      mitreTechnique: "T1486, T1490, T1021.001",
      containmentActions: "Network isolation applied to prod-node-01,02,03. Firewall rules updated. C2 domains blocked.",
      timeToDetect: 23,
    },
    {
      title: "Supply Chain Compromise — npm Dependency",
      description: "Malicious package lodash-utils@3.2.1 identified exfiltrating environment variables on import. Package injected via compromised maintainer account. All downstream services at risk.",
      severity: "critical",
      status: "contained",
      type: "supply_chain",
      assignedAgentId: engAgent?.id,
      affectedSystems: "all Node.js services using lodash-utils@3.2.1",
      iocIndicators: "lodash-utils@3.2.1, npm registry compromise, C2: supply-updates[.]net",
      playbookSteps: "1. Remove malicious package\n2. Rotate all exposed secrets\n3. Audit all downstream dependencies\n4. Notify affected teams\n5. Submit security advisory",
      attackVector: "Compromised npm maintainer account → malicious package publish",
      mitreTechnique: "T1195.001",
      containmentActions: "Package removed from registry mirror. All secrets rotated. Environment variables audited.",
      timeToDetect: 47,
    },
    {
      title: "Insider Threat — Unauthorized Data Access",
      description: "Anomalous data access patterns detected on user account EMP-4471. Large volume downloads of customer PII records outside business hours. UEBA model confidence: 94%.",
      severity: "high",
      status: "investigating",
      type: "insider_threat",
      assignedAgentId: secAgent?.id,
      affectedSystems: "customer-db-prod, data-warehouse, analytics-platform",
      iocIndicators: "User: EMP-4471, 2.3GB download, 03:00-04:30 UTC, IP: 10.4.22.91",
      playbookSteps: "1. Preserve access logs\n2. Disable account\n3. Legal hold notification\n4. HR involvement\n5. Forensic analysis\n6. Data breach assessment",
      attackVector: "Legitimate credentials — behavioral anomaly",
      mitreTechnique: "T1078, T1530",
      containmentActions: "Account suspended. Manager notified. Legal hold issued.",
      timeToDetect: 310,
    },
    {
      title: "Phishing Campaign — Executive Impersonation",
      description: "Coordinated spear-phishing campaign targeting finance team. 12 employees received emails impersonating CEO requesting wire transfers. 2 employees clicked credential harvesting links.",
      severity: "high",
      status: "contained",
      type: "phishing",
      assignedAgentId: secAgent?.id,
      affectedSystems: "email-gateway, 2 employee workstations (WS-0412, WS-0819)",
      iocIndicators: "ceo-rapidforce[.]com, harvester IP: 45.142.212.100, credential portal clone",
      playbookSteps: "1. Block phishing domains\n2. Reset compromised credentials\n3. Scan workstations for persistence\n4. Security awareness notification\n5. Email gateway rule update",
      attackVector: "Spear phishing → credential harvesting → potential account takeover",
      mitreTechnique: "T1566.002, T1078",
      containmentActions: "Domains blocked. Credentials reset. Workstations reimaged.",
      timeToDetect: 85,
    },
    {
      title: "Container Escape — Kubernetes Node Compromise",
      description: "Red team exercise uncovered a container escape via cgroup v1 release_agent exploit. Affected node achieved root access on host. Patching in progress.",
      severity: "high",
      status: "eradicated",
      type: "privilege_escalation",
      assignedAgentId: redAgent?.id,
      affectedSystems: "k8s-worker-node-07, k8s-worker-node-08",
      iocIndicators: "cgroup escape via /sys/fs/cgroup/release_agent, CAP_SYS_ADMIN abuse",
      playbookSteps: "1. Cordon and drain affected nodes\n2. Apply kernel patch\n3. Update pod security policies\n4. Redeploy with restricted capabilities\n5. Validate fix with red team",
      attackVector: "Privileged container → cgroup escape → host root access",
      mitreTechnique: "T1611",
      containmentActions: "Nodes cordoned. Kernel patched. Pod security admission enforced.",
      timeToDetect: 180,
    },
    {
      title: "Lateral Movement — Pass-the-Hash Detected",
      description: "Pass-the-hash attack detected across 4 domain-joined workstations. Authentication logs show NTLM Type 3 with empty workstation names. Attacker likely pivoting toward domain controller.",
      severity: "critical",
      status: "open",
      type: "lateral_movement",
      affectedSystems: "WS-0101, WS-0205, WS-0411, WS-0520, DC-01 (target)",
      iocIndicators: "NTLM hash reuse, EventID 4624 LogonType 3 pattern, NtLmSsp",
      playbookSteps: "1. Identify compromised accounts\n2. Reset NTLM hashes\n3. Enable Protected Users group\n4. Block NTLM where possible\n5. Monitor DC access",
      attackVector: "Credential dumping → NTLM hash extraction → lateral movement",
      mitreTechnique: "T1550.002, T1003.001",
      containmentActions: "Investigating — containment in progress",
      timeToDetect: 15,
    },
    {
      title: "DDoS Attack — API Gateway Layer 7",
      description: "Volumetric application-layer DDoS targeting /api/auth endpoint. 450k requests/second from 3 botnet clusters. Rate limiting and WAF rules deployed. Attack ongoing.",
      severity: "medium",
      status: "investigating",
      type: "ddos",
      affectedSystems: "api-gateway-prod, auth-service, load-balancer-01",
      iocIndicators: "ASN: AS9009, AS202448, AS44477 — known DDoS-for-hire infrastructure",
      playbookSteps: "1. Enable Cloudflare Under Attack Mode\n2. Rate limit /api/auth endpoint\n3. Add WAF rules for bot signatures\n4. Notify upstream provider\n5. Monitor legitimate traffic impact",
      attackVector: "Botnet HTTP flood — Layer 7 application DDoS",
      mitreTechnique: "T1498.002",
      containmentActions: "WAF rules active. Rate limiting enforced. Upstream scrubbing engaged.",
      timeToDetect: 3,
    },
    {
      title: "Zero-Day Exploitation — HTTP/2 Stack",
      description: "Active exploitation of CVE-2026-8821 detected against internal HTTP/2 endpoints. Memory corruption leading to RCE confirmed in staging environment. Emergency patch deployment initiated.",
      severity: "critical",
      status: "open",
      type: "zero_day",
      affectedSystems: "api-server, internal-gateway, 4 microservices",
      iocIndicators: "CVE-2026-8821, anomalous HTTP/2 CONTINUATION frames, heap corruption pattern",
      playbookSteps: "1. Emergency patch deployment\n2. WAF virtual patch for CVE\n3. Isolate unpatched services\n4. Monitor for exploitation indicators\n5. Validate patch effectiveness",
      attackVector: "HTTP/2 stream multiplexer memory corruption → RCE",
      mitreTechnique: "T1190",
      containmentActions: "Virtual WAF patch deployed. Services behind proxy. Patch in deployment queue.",
      timeToDetect: 8,
    },
  ]);

  console.log("Incidents seeded.");
  console.log("All done.");
  process.exit(0);
}

seedDetectionsAndIncidents().catch((err) => {
  console.error(err);
  process.exit(1);
});
