import { Router, type IRouter } from "express";
import healthRouter        from "./health";
import agentsRouter        from "./agents";
import sprintsRouter       from "./sprints";
import missionsRouter      from "./missions";
import threatsRouter       from "./threats";
import activityRouter      from "./activity";
import detectionsRouter    from "./detections";
import incidentsRouter     from "./incidents";
import copilotRouter       from "./copilot";
import authRouter          from "./auth";
import licensesRouter      from "./licenses";
import adminRouter         from "./admin";
import vouchersRouter      from "./vouchers";
import announcementsRouter from "./announcements";
import complianceRouter    from "./compliance";
import uebaRouter          from "./ueba";
import playbooksRouter     from "./playbooks";
import executiveRouter     from "./executive";
import ewsRouter           from "./ews";
import eventsRouter        from "./events";
import correlationsRouter  from "./correlations";
import actionsRouter       from "./actions";
import riskRouter          from "./risk";

const router: IRouter = Router();

router.use(authRouter);
router.use(licensesRouter);
router.use(adminRouter);
router.use(vouchersRouter);
router.use(announcementsRouter);
router.use(healthRouter);
router.use(agentsRouter);
router.use(sprintsRouter);
router.use(missionsRouter);
router.use(threatsRouter);
router.use(activityRouter);
router.use(detectionsRouter);
router.use(incidentsRouter);
router.use(copilotRouter);
router.use(complianceRouter);
router.use(uebaRouter);
router.use(playbooksRouter);
router.use(executiveRouter);
router.use(ewsRouter);
router.use(eventsRouter);
router.use(correlationsRouter);
router.use(actionsRouter);
router.use(riskRouter);

export default router;
