import { Router } from "express";
import { db, pluginsTable } from "@workspace/db";
import { eq, desc } from "drizzle-orm";
import { requireAuth } from "../middleware/requireAuth";

const router = Router();

const SEED_PLUGINS = [
  { name: "Slack", slug: "slack", description: "Send real-time SOC alerts, incident notifications, and AI briefings directly to Slack channels.", longDesc: "Integrate Rapid Force with your Slack workspace to deliver real-time security alerts, incident updates, playbook execution notifications, and AI-generated briefings to designated channels. Supports thread-based conversations and interactive approve/reject buttons for human-in-the-loop workflows.", author: "Slack Technologies", version: "2.4.1", category: "notification" as const, icon: "slack", capabilities: JSON.stringify(["Send alert notifications", "Incident channel creation", "Interactive approval buttons", "Daily briefing delivery", "Threat intel sharing"]), configSchema: JSON.stringify({ fields: [{ key: "botToken", label: "Bot OAuth Token", type: "password", placeholder: "xoxb-...", required: true }, { key: "signingSecret", label: "Signing Secret", type: "password", placeholder: "Your Slack app signing secret", required: true }, { key: "defaultChannel", label: "Default Alert Channel", type: "text", placeholder: "#soc-alerts", required: true }, { key: "briefingChannel", label: "Briefing Channel", type: "text", placeholder: "#executive-briefings", required: false }] }), isBuiltIn: true, installCount: 8420, rating: 48, reviewCount: 312 },
  { name: "PagerDuty", slug: "pagerduty", description: "Auto-escalate critical incidents to on-call responders with full incident context and severity routing.", longDesc: "Route critical incidents and EWS predictions directly to PagerDuty on-call schedules. Supports severity-based routing, auto-resolve on containment, and bi-directional sync of incident status between Rapid Force and PagerDuty.", author: "PagerDuty Inc.", version: "3.1.0", category: "ir_tools" as const, icon: "bell", capabilities: JSON.stringify(["On-call escalation", "Severity routing", "Auto-resolve sync", "Incident bi-directional sync", "Runbook linking"]), configSchema: JSON.stringify({ fields: [{ key: "apiKey", label: "API Key", type: "password", placeholder: "u+xxxx...", required: true }, { key: "routingKey", label: "Events API Routing Key", type: "password", placeholder: "R...", required: true }, { key: "defaultUrgency", label: "Default Urgency", type: "select", options: ["high", "low"], required: false }] }), isBuiltIn: true, installCount: 6103, rating: 47, reviewCount: 218 },
  { name: "Jira", slug: "jira", description: "Auto-create Jira tickets for incidents and vulnerabilities with MITRE ATT&CK mapping and evidence.", longDesc: "Automatically create, update, and close Jira issues from Rapid Force incidents and playbook executions. Maps MITRE ATT&CK techniques to issue labels, attaches forensic evidence, and tracks remediation SLAs.", author: "Atlassian", version: "4.0.2", category: "ticketing" as const, icon: "ticket", capabilities: JSON.stringify(["Auto ticket creation", "MITRE technique labeling", "Evidence attachment", "SLA tracking", "Status bi-sync"]), configSchema: JSON.stringify({ fields: [{ key: "baseUrl", label: "Jira Instance URL", type: "url", placeholder: "https://yourorg.atlassian.net", required: true }, { key: "email", label: "Account Email", type: "email", placeholder: "you@company.com", required: true }, { key: "apiToken", label: "API Token", type: "password", placeholder: "Your Atlassian API token", required: true }, { key: "projectKey", label: "Project Key", type: "text", placeholder: "SOC", required: true }, { key: "issueType", label: "Issue Type", type: "select", options: ["Bug", "Task", "Story", "Incident"], required: false }] }), isBuiltIn: true, installCount: 11237, rating: 46, reviewCount: 489 },
  { name: "ServiceNow", slug: "servicenow", description: "Enterprise ITSM integration for incident ticket creation, CMDB asset sync, and change management workflows.", longDesc: "Enterprise-grade ServiceNow integration for creating and updating security incidents in the CMDB, syncing asset inventory with the Rapid Force asset database, and triggering change management workflows for remediation actions.", author: "ServiceNow", version: "2.8.0", category: "ticketing" as const, icon: "layers", capabilities: JSON.stringify(["CMDB asset sync", "Incident ticket creation", "Change management trigger", "SLA enforcement", "Knowledge article linking"]), configSchema: JSON.stringify({ fields: [{ key: "instanceUrl", label: "Instance URL", type: "url", placeholder: "https://yourorg.service-now.com", required: true }, { key: "username", label: "Service Account Username", type: "text", placeholder: "svc_rapidforce", required: true }, { key: "password", label: "Service Account Password", type: "password", placeholder: "•••••••••", required: true }, { key: "assignmentGroup", label: "Default Assignment Group", type: "text", placeholder: "Security Operations", required: false }] }), isBuiltIn: false, installCount: 4891, rating: 45, reviewCount: 176 },
  { name: "VirusTotal", slug: "virustotal", description: "Automatic IOC enrichment with VirusTotal multi-engine scanning for hashes, IPs, domains, and URLs.", longDesc: "Enrich every IOC ingested by Rapid Force with VirusTotal intelligence — file hashes, IP addresses, domains, and URLs are automatically scanned across 70+ AV engines. Results feed back into threat scoring and detection rules.", author: "Google Chronicle", version: "1.5.3", category: "threat_intel" as const, icon: "search", capabilities: JSON.stringify(["Hash/IP/domain/URL scan", "Multi-engine results", "IOC risk scoring", "Malware family identification", "Feed enrichment"]), configSchema: JSON.stringify({ fields: [{ key: "apiKey", label: "VirusTotal API Key", type: "password", placeholder: "Your VT API key (free or premium)", required: true }, { key: "premium", label: "Premium API Access", type: "select", options: ["Yes", "No"], required: false }] }), isBuiltIn: true, installCount: 15603, rating: 49, reviewCount: 702 },
  { name: "CrowdStrike Falcon", slug: "crowdstrike", description: "Deep EDR integration for real-time endpoint telemetry, process trees, and one-click containment.", longDesc: "Connect Rapid Force to CrowdStrike Falcon for full EDR visibility — receive endpoint detections, pull process trees and memory dumps for forensics, and execute containment actions (host isolation, process kill) directly from incident response workflows.", author: "CrowdStrike", version: "5.2.0", category: "ir_tools" as const, icon: "shield", capabilities: JSON.stringify(["Endpoint detection ingestion", "Process tree visualization", "Host isolation", "RTR script execution", "Threat graph correlation"]), configSchema: JSON.stringify({ fields: [{ key: "clientId", label: "OAuth2 Client ID", type: "text", placeholder: "Your Falcon API client ID", required: true }, { key: "clientSecret", label: "OAuth2 Client Secret", type: "password", placeholder: "Your Falcon API client secret", required: true }, { key: "baseUrl", label: "API Base URL", type: "select", options: ["https://api.crowdstrike.com", "https://api.us-2.crowdstrike.com", "https://api.eu-1.crowdstrike.com"], required: true }] }), isBuiltIn: false, installCount: 9847, rating: 49, reviewCount: 521 },
  { name: "Splunk SIEM", slug: "splunk", description: "Bidirectional Splunk integration for alert ingestion, SPL query execution, and data export.", longDesc: "Ingest Splunk alerts and notable events into Rapid Force as incidents, execute SPL queries for threat hunting, and export investigation results back to Splunk for long-term retention. Supports both Splunk Cloud and on-premises deployments.", author: "Splunk Inc.", version: "3.7.1", category: "siem" as const, icon: "database", capabilities: JSON.stringify(["Alert ingestion", "SPL query execution", "Notable event sync", "Saved search trigger", "Data export"]), configSchema: JSON.stringify({ fields: [{ key: "baseUrl", label: "Splunk Host URL", type: "url", placeholder: "https://splunk.yourorg.com:8089", required: true }, { key: "token", label: "HTTP Event Collector Token", type: "password", placeholder: "HEC or API auth token", required: true }, { key: "index", label: "Target Index", type: "text", placeholder: "security_events", required: false }, { key: "verifySsl", label: "Verify SSL Certificate", type: "select", options: ["Yes", "No"], required: false }] }), isBuiltIn: false, installCount: 7234, rating: 47, reviewCount: 298 },
  { name: "AWS Security Hub", slug: "aws-security-hub", description: "Aggregate AWS Security Hub findings from GuardDuty, Inspector, and Macie into Rapid Force.", longDesc: "Centralize AWS security findings from GuardDuty, Inspector, Macie, IAM Access Analyzer, and third-party integrations into Rapid Force. Auto-maps findings to MITRE ATT&CK and creates incidents for critical findings.", author: "Amazon Web Services", version: "2.1.4", category: "cloud_security" as const, icon: "cloud", capabilities: JSON.stringify(["GuardDuty finding ingestion", "Inspector vulnerability sync", "Macie DLP alerts", "MITRE mapping", "Multi-account aggregation"]), configSchema: JSON.stringify({ fields: [{ key: "accessKeyId", label: "AWS Access Key ID", type: "text", placeholder: "AKIA...", required: true }, { key: "secretAccessKey", label: "AWS Secret Access Key", type: "password", placeholder: "Your AWS secret access key", required: true }, { key: "region", label: "AWS Region", type: "text", placeholder: "us-east-1", required: true }, { key: "accountIds", label: "Additional Account IDs (optional)", type: "text", placeholder: "123456789,987654321", required: false }] }), isBuiltIn: false, installCount: 5621, rating: 46, reviewCount: 203 },
  { name: "Microsoft Sentinel", slug: "ms-sentinel", description: "Ingest Microsoft Sentinel incidents and UEBA alerts with full KQL query support.", longDesc: "Connect to Microsoft Sentinel for bidirectional incident sync, KQL query execution for threat hunting, and UEBA alert ingestion. Supports Azure AD identity risk signals and Microsoft Defender for Endpoint telemetry.", author: "Microsoft", version: "4.3.0", category: "siem" as const, icon: "monitor", capabilities: JSON.stringify(["Incident bi-sync", "KQL query execution", "UEBA alert ingestion", "Azure AD risk signals", "Defender telemetry"]), configSchema: JSON.stringify({ fields: [{ key: "tenantId", label: "Azure Tenant ID", type: "text", placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", required: true }, { key: "clientId", label: "App Registration Client ID", type: "text", placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", required: true }, { key: "clientSecret", label: "Client Secret", type: "password", placeholder: "Your app registration secret", required: true }, { key: "workspaceId", label: "Log Analytics Workspace ID", type: "text", placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", required: true }, { key: "subscriptionId", label: "Azure Subscription ID", type: "text", placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", required: true }] }), isBuiltIn: false, installCount: 6893, rating: 47, reviewCount: 334 },
  { name: "Okta", slug: "okta", description: "Identity risk signals, suspicious login detection, and automated account lockout from Okta.", longDesc: "Integrate Okta identity signals into Rapid Force for real-time suspicious login detection, geo-impossible travel alerts, MFA bypass attempts, and automated account lockout actions through playbooks and autonomous response.", author: "Okta Inc.", version: "2.6.0", category: "identity" as const, icon: "key", capabilities: JSON.stringify(["Suspicious login signals", "Geo-impossible travel", "MFA bypass detection", "Auto account lockout", "Session revocation"]), configSchema: JSON.stringify({ fields: [{ key: "orgUrl", label: "Okta Organization URL", type: "url", placeholder: "https://yourorg.okta.com", required: true }, { key: "apiToken", label: "API Token", type: "password", placeholder: "00...", required: true }, { key: "webhookSecret", label: "Event Hook Secret (optional)", type: "password", placeholder: "For real-time event delivery", required: false }] }), isBuiltIn: false, installCount: 8102, rating: 48, reviewCount: 411 },
  { name: "Tenable Nessus", slug: "tenable", description: "Vulnerability scan results and asset risk scoring synced directly into Rapid Force.", longDesc: "Import Tenable vulnerability scan results into Rapid Force asset risk scores. Correlate vulnerabilities with active threats and incidents, prioritize remediation using real-world exploitation data, and auto-create tickets for critical CVEs.", author: "Tenable Inc.", version: "3.2.1", category: "vulnerability" as const, icon: "alert-triangle", capabilities: JSON.stringify(["Vulnerability import", "Asset risk scoring", "CVE correlation", "Exploit likelihood scoring", "Remediation ticket creation"]), configSchema: JSON.stringify({ fields: [{ key: "accessKey", label: "Access Key", type: "text", placeholder: "Your Tenable.io access key", required: true }, { key: "secretKey", label: "Secret Key", type: "password", placeholder: "Your Tenable.io secret key", required: true }, { key: "baseUrl", label: "API Base URL", type: "select", options: ["https://cloud.tenable.com", "https://on-prem-tenable:8834"], required: false }] }), isBuiltIn: false, installCount: 4312, rating: 45, reviewCount: 167 },
  { name: "TheHive", slug: "thehive", description: "Open-source IR platform integration for case management, observable sharing, and Cortex analyzer results.", longDesc: "Bridge Rapid Force with TheHive for collaborative incident case management. Share observables (IOCs) between platforms, trigger Cortex analyzers, and sync case status for cross-team IR workflows.", author: "StrangeBee", version: "1.8.2", category: "ir_tools" as const, icon: "git-branch", capabilities: JSON.stringify(["Case sync", "Observable sharing", "Cortex analyzer trigger", "MISP integration relay", "Analyst collaboration"]), configSchema: JSON.stringify({ fields: [{ key: "apiUrl", label: "TheHive API URL", type: "url", placeholder: "http://thehive.yourorg.local:9000", required: true }, { key: "apiKey", label: "API Key", type: "password", placeholder: "Your TheHive API key", required: true }, { key: "organisation", label: "Organisation Name", type: "text", placeholder: "YOUR_ORG", required: false }, { key: "cortexUrl", label: "Cortex URL (optional)", type: "url", placeholder: "http://cortex.yourorg.local:9001", required: false }] }), isBuiltIn: false, installCount: 3187, rating: 44, reviewCount: 98 },
];

async function seedIfEmpty() {
  const existing = await db.select({ id: pluginsTable.id }).from(pluginsTable).limit(1);
  if (existing.length === 0) {
    await db.insert(pluginsTable).values(SEED_PLUGINS);
  }
}

router.get("/plugins", requireAuth, async (req, res) => {
  try {
    await seedIfEmpty();
    const plugins = await db.select().from(pluginsTable).orderBy(desc(pluginsTable.installCount));
    res.json(plugins.map(p => ({ ...p, capabilities: JSON.parse(p.capabilities), configSchema: JSON.parse(p.configSchema) })));
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/plugins/:slug/install", requireAuth, async (req, res) => {
  try {
    await seedIfEmpty();
    const [plugin] = await db.select().from(pluginsTable).where(eq(pluginsTable.slug, req.params.slug));
    if (!plugin) { res.status(404).json({ error: "Plugin not found" }); return; }
    const [updated] = await db.update(pluginsTable)
      .set({ isInstalled: true, isEnabled: true, installCount: plugin.installCount + 1, updatedAt: new Date() })
      .where(eq(pluginsTable.slug, req.params.slug)).returning();
    res.json({ ...updated, capabilities: JSON.parse(updated.capabilities), configSchema: JSON.parse(updated.configSchema) });
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/plugins/:slug/uninstall", requireAuth, async (req, res) => {
  try {
    const [updated] = await db.update(pluginsTable)
      .set({ isInstalled: false, isEnabled: false, updatedAt: new Date() })
      .where(eq(pluginsTable.slug, req.params.slug)).returning();
    if (!updated) { res.status(404).json({ error: "Plugin not found" }); return; }
    res.json({ ...updated, capabilities: JSON.parse(updated.capabilities), configSchema: JSON.parse(updated.configSchema) });
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.patch("/plugins/:slug/toggle", requireAuth, async (req, res) => {
  try {
    const { enabled } = req.body;
    const [updated] = await db.update(pluginsTable)
      .set({ isEnabled: enabled, updatedAt: new Date() })
      .where(eq(pluginsTable.slug, req.params.slug)).returning();
    if (!updated) { res.status(404).json({ error: "Plugin not found" }); return; }
    res.json({ ...updated, capabilities: JSON.parse(updated.capabilities), configSchema: JSON.parse(updated.configSchema) });
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.patch("/plugins/:slug/config", requireAuth, async (req, res) => {
  try {
    const { config } = req.body;
    const [existing] = await db.select().from(pluginsTable).where(eq(pluginsTable.slug, req.params.slug));
    if (!existing) { res.status(404).json({ error: "Plugin not found" }); return; }
    const [updated] = await db.update(pluginsTable)
      .set({ updatedAt: new Date(), configSchema: existing.configSchema })
      .where(eq(pluginsTable.slug, req.params.slug)).returning();
    if (!updated) { res.status(404).json({ error: "Plugin not found" }); return; }
    res.json({ ...updated, capabilities: JSON.parse(updated.capabilities), configSchema: JSON.parse(updated.configSchema), savedConfig: config });
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

export default router;
