import { Router } from "express";
import { db, ruleVersionsTable, ruleReviewsTable, detectionsTable } from "@workspace/db";
import { eq, desc, and } from "drizzle-orm";
import { requireAuth } from "../middleware/requireAuth";

const router = Router();

const COMMUNITY_RULES = [
  // ─── SigmaHQ ───────────────────────────────────────────────────────────────
  { source: "SigmaHQ", name: "Windows LSASS Memory Dump via ProcDump", type: "sigma", severity: "high", mitreTechnique: "T1003.001", mitreTactic: "Credential Access", description: "Detects credential dumping via Sysinternals ProcDump targeting lsass.exe", ruleContent: `title: LSASS Memory Dump via ProcDump\nstatus: stable\ndescription: Detects credential dumping via Sysinternals ProcDump targeting lsass.exe\nauthor: Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith: '\\\\procdump.exe'\n    CommandLine|contains: 'lsass'\n  condition: selection\nlevel: high\ntags:\n  - attack.credential_access\n  - attack.t1003.001`, author: "Florian Roth (SigmaHQ)", tags: "lsass,credential-access,procdump", version: "1.3" },
  { source: "SigmaHQ", name: "PowerShell Download Cradle", type: "sigma", severity: "medium", mitreTechnique: "T1059.001", mitreTactic: "Execution", description: "Detects PowerShell command-line download cradles used for payload delivery", ruleContent: `title: PowerShell Download Cradle\nstatus: stable\nauthor: Harish Segar\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    CommandLine|contains:\n      - 'IEX (New-Object'\n      - 'IEX(New-Object'\n      - 'Invoke-Expression'\n  condition: selection\nlevel: medium\ntags:\n  - attack.execution\n  - attack.t1059.001`, author: "Harish Segar (SigmaHQ)", tags: "powershell,execution,download", version: "2.0" },
  { source: "SigmaHQ", name: "PowerShell Empire Activity", type: "sigma", severity: "high", mitreTechnique: "T1059.001", mitreTactic: "Execution", description: "Detects PowerShell Empire staging and beaconing indicators", ruleContent: `title: PowerShell Empire Activity\nstatus: stable\nauthor: Willi Ballenthin\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    CommandLine|contains:\n      - 'PowerShell Empire'\n      - 'http://127.0.0.1:8080'\n      - 'Invoke-Empire'\n  condition: selection\nlevel: high\ntags:\n  - attack.execution\n  - attack.t1059.001`, author: "Willi Ballenthin (SigmaHQ)", tags: "empire,powershell,c2", version: "1.0" },
  { source: "SigmaHQ", name: "WMI Persistence via Event Subscription", type: "sigma", severity: "high", mitreTechnique: "T1546.003", mitreTactic: "Persistence", description: "Detects WMI event subscription persistence modifications", ruleContent: `title: WMI Persistence via Event Subscription\nstatus: stable\nauthor: Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    CommandLine|contains:\n      - '__EventFilter'\n      - '__FilterToConsumerBinding'\n      - 'CommandLineEventConsumer'\n  condition: selection\nlevel: high\ntags:\n  - attack.persistence\n  - attack.t1546.003`, author: "Florian Roth (SigmaHQ)", tags: "wmi,persistence,subscription", version: "1.0" },
  { source: "SigmaHQ", name: "Suspicious Scheduled Task Creation", type: "sigma", severity: "medium", mitreTechnique: "T1053.005", mitreTactic: "Persistence", description: "Detects suspicious scheduled task creation via schtasks.exe or PowerShell", ruleContent: `title: Suspicious Scheduled Task Creation\nstatus: stable\nauthor: Nasreddine Bencherchali\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith: '\\\\schtasks.exe'\n    CommandLine|contains: '/create'\n  filter:\n    CommandLine|contains:\n      - 'Microsoft'\n      - 'Windows'\n  condition: selection and not filter\nlevel: medium\ntags:\n  - attack.persistence\n  - attack.t1053.005`, author: "Nasreddine Bencherchali (SigmaHQ)", tags: "persistence,scheduled-task,windows", version: "2.1" },
  { source: "SigmaHQ", name: "Mimikatz Command Line Indicators", type: "sigma", severity: "critical", mitreTechnique: "T1003.001", mitreTactic: "Credential Access", description: "Detects common Mimikatz command-line arguments used for credential dumping", ruleContent: `title: Mimikatz Command Line Indicators\nstatus: stable\nauthor: Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    CommandLine|contains:\n      - 'sekurlsa::'\n      - 'lsadump::'\n      - 'kerberos::'\n      - 'privilege::debug'\n      - 'crypto::capi'\n  condition: selection\nlevel: critical\ntags:\n  - attack.credential_access\n  - attack.t1003.001`, author: "Florian Roth (SigmaHQ)", tags: "mimikatz,credential-access,critical", version: "2.4" },
  { source: "SigmaHQ", name: "Lateral Movement via SMB Named Pipe", type: "sigma", severity: "high", mitreTechnique: "T1021.002", mitreTactic: "Lateral Movement", description: "Detects lateral movement using SMB named pipes commonly abused by Cobalt Strike and Impacket", ruleContent: `title: Lateral Movement via SMB Named Pipe\nstatus: experimental\nauthor: Rapid Force Labs\nlogsource:\n  product: windows\n  service: security\ndetection:\n  selection:\n    EventID: 5145\n    ShareName: '\\\\\\\\*\\\\IPC$'\n    RelativeTargetName|contains:\n      - 'msagent'\n      - 'status_'\n      - 'mojo.'\n      - 'wkssvc'\n  condition: selection\nlevel: high\ntags:\n  - attack.lateral_movement\n  - attack.t1021.002`, author: "Rapid Force Labs", tags: "lateral-movement,smb,named-pipe", version: "1.1" },
  { source: "SigmaHQ", name: "WMI Spawning Windows Shell", type: "sigma", severity: "high", mitreTechnique: "T1047", mitreTactic: "Execution", description: "Detects WMI spawning cmd.exe or powershell.exe — common lateral movement and execution technique", ruleContent: `title: WMI Spawning Windows Shell\nstatus: stable\nauthor: Michael Haag\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    ParentImage|endswith: '\\\\WmiPrvSE.exe'\n    Image|endswith:\n      - '\\\\cmd.exe'\n      - '\\\\powershell.exe'\n      - '\\\\wscript.exe'\n      - '\\\\cscript.exe'\n  condition: selection\nlevel: high\ntags:\n  - attack.execution\n  - attack.t1047`, author: "Michael Haag (SigmaHQ)", tags: "wmi,execution,lateral-movement", version: "2.0" },
  { source: "SigmaHQ", name: "NTDS.dit File Access", type: "sigma", severity: "critical", mitreTechnique: "T1003.003", mitreTactic: "Credential Access", description: "Detects attempts to access NTDS.dit file which contains all Active Directory password hashes", ruleContent: `title: NTDS.dit File Access\nstatus: stable\nauthor: Thomas Patzke\nlogsource:\n  product: windows\n  service: security\ndetection:\n  selection:\n    EventID: 4663\n    ObjectName|contains: '\\\\ntds.dit'\n  condition: selection\nlevel: critical\ntags:\n  - attack.credential_access\n  - attack.t1003.003`, author: "Thomas Patzke (SigmaHQ)", tags: "ntds,active-directory,credential-access", version: "1.5" },
  { source: "SigmaHQ", name: "PsExec Tool Execution", type: "sigma", severity: "medium", mitreTechnique: "T1569.002", mitreTactic: "Execution", description: "Detects use of Sysinternals PsExec — commonly used for lateral movement and remote execution", ruleContent: `title: PsExec Tool Execution\nstatus: stable\nauthor: Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection_image:\n    Image|endswith: '\\\\PsExec.exe'\n  selection_service:\n    ImagePath|contains: 'PSEXESVC.exe'\n  condition: 1 of selection_*\nlevel: medium\ntags:\n  - attack.execution\n  - attack.t1569.002`, author: "Florian Roth (SigmaHQ)", tags: "psexec,lateral-movement,remote-execution", version: "3.1" },
  { source: "SigmaHQ", name: "Registry Run Key Persistence", type: "sigma", severity: "medium", mitreTechnique: "T1547.001", mitreTactic: "Persistence", description: "Detects modification of Run/RunOnce registry keys for persistence — classic malware technique", ruleContent: `title: Registry Run Key Persistence\nstatus: stable\nauthor: Florian Roth, Markus Neis\nlogsource:\n  category: registry_set\n  product: windows\ndetection:\n  selection:\n    TargetObject|contains:\n      - '\\\\SOFTWARE\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run'\n      - '\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Winlogon'\n  filter:\n    Details|contains:\n      - 'C:\\\\Windows\\\\system32'\n      - 'C:\\\\Program Files'\n  condition: selection and not filter\nlevel: medium\ntags:\n  - attack.persistence\n  - attack.t1547.001`, author: "Florian Roth (SigmaHQ)", tags: "registry,persistence,run-key", version: "2.3" },
  { source: "SigmaHQ", name: "Net.exe Reconnaissance Activity", type: "sigma", severity: "low", mitreTechnique: "T1087.002", mitreTactic: "Discovery", description: "Detects common net.exe commands used for domain and user enumeration during reconnaissance", ruleContent: `title: Net.exe Reconnaissance Activity\nstatus: stable\nauthor: Michael Haag, Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith: '\\\\net.exe'\n    CommandLine|contains:\n      - ' user '\n      - ' group '\n      - ' localgroup '\n      - ' accounts '\n      - ' share '\n  condition: selection\nlevel: low\ntags:\n  - attack.discovery\n  - attack.t1087.002`, author: "Michael Haag (SigmaHQ)", tags: "net,discovery,enumeration", version: "2.0" },
  { source: "SigmaHQ", name: "Shadow Copy Deletion via WMIC or VSSAdmin", type: "sigma", severity: "critical", mitreTechnique: "T1490", mitreTactic: "Impact", description: "Detects shadow copy deletion — critical ransomware indicator used to prevent recovery", ruleContent: `title: Shadow Copy Deletion via WMIC or VSSAdmin\nstatus: stable\nauthor: Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection_wmic:\n    Image|endswith: '\\\\wmic.exe'\n    CommandLine|contains:\n      - 'shadowcopy delete'\n      - 'shadow delete'\n  selection_vss:\n    Image|endswith: '\\\\vssadmin.exe'\n    CommandLine|contains: 'delete shadows'\n  condition: 1 of selection_*\nlevel: critical\ntags:\n  - attack.impact\n  - attack.t1490`, author: "Florian Roth (SigmaHQ)", tags: "ransomware,shadow-copy,impact", version: "2.2" },
  { source: "SigmaHQ", name: "Certutil Download or Decode", type: "sigma", severity: "medium", mitreTechnique: "T1105", mitreTactic: "Command and Control", description: "Detects certutil.exe used for downloading files or decoding base64 — LOLBAS abuse", ruleContent: `title: Certutil Download or Decode\nstatus: stable\nauthor: juju4\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    Image|endswith: '\\\\certutil.exe'\n    CommandLine|contains:\n      - '-urlcache'\n      - '-decode'\n      - '-decodehex'\n      - 'http'\n  condition: selection\nlevel: medium\ntags:\n  - attack.command_and_control\n  - attack.t1105`, author: "juju4 (SigmaHQ)", tags: "certutil,lolbas,download", version: "2.1" },
  { source: "SigmaHQ", name: "Kerberoasting Activity", type: "sigma", severity: "high", mitreTechnique: "T1558.003", mitreTactic: "Credential Access", description: "Detects Kerberoasting — requesting service tickets for offline cracking of service account passwords", ruleContent: `title: Kerberoasting Activity\nstatus: stable\nauthor: Timur Zinniatullin\nlogsource:\n  product: windows\n  service: security\ndetection:\n  selection:\n    EventID: 4769\n    ServiceName|endswith: '$'\n    TicketEncryptionType: '0x17'\n  condition: selection\nlevel: high\ntags:\n  - attack.credential_access\n  - attack.t1558.003`, author: "Timur Zinniatullin (SigmaHQ)", tags: "kerberoasting,active-directory,credential-access", version: "1.4" },
  { source: "SigmaHQ", name: "DCSync Attack via Mimikatz lsadump", type: "sigma", severity: "critical", mitreTechnique: "T1003.006", mitreTactic: "Credential Access", description: "Detects DCSync attack using directory replication to dump password hashes from domain controller", ruleContent: `title: DCSync Attack via Mimikatz lsadump\nstatus: stable\nauthor: Benjamin Delpy\nlogsource:\n  product: windows\n  service: security\ndetection:\n  selection:\n    EventID:\n      - 4662\n    Properties|contains:\n      - '1131f6aa-9c07-11d1-f79f-00c04fc2dcd2'\n      - '1131f6ad-9c07-11d1-f79f-00c04fc2dcd2'\n  filter:\n    SubjectUserName|endswith: '$'\n  condition: selection and not filter\nlevel: critical\ntags:\n  - attack.credential_access\n  - attack.t1003.006`, author: "Benjamin Delpy (SigmaHQ)", tags: "dcsync,mimikatz,domain-controller", version: "1.2" },
  // ─── YARA-Forge / Signature-Base ───────────────────────────────────────────
  { source: "YARA-Forge", name: "Cobalt Strike Beacon Memory", type: "yara", severity: "critical", mitreTechnique: "T1071.001", mitreTactic: "Command and Control", description: "Detects Cobalt Strike beacon reflective DLL in memory — identifies C2 beaconing activity", ruleContent: `rule CobaltStrike_Beacon_Reflective_DLL {\n  meta:\n    description = "Detects Cobalt Strike beacon in memory via reflective loader"\n    author = "Rapid Force Labs"\n    source = "YARA-Forge / signature-base"\n    severity = "critical"\n    mitre_technique = "T1071.001"\n    date = "2024-11-01"\n  strings:\n    $rfl1 = "ReflectivLoader" ascii nocase\n    $rfl2 = { 4D 5A 41 52 55 48 89 E5 }\n    $cs_str1 = "beacon.x64.dll" ascii nocase\n    $cs_str2 = "CDN_API_KEY" ascii\n    $pipe1 = "\\\\\\\\.\\\\pipe\\\\msagent_" wide ascii\n    $pipe2 = "\\\\\\\\.\\\\pipe\\\\status_" wide ascii\n  condition:\n    ($rfl1 or $rfl2) and (1 of ($cs_str*) or 1 of ($pipe*))\n}`, author: "Rapid Force Labs / YARA-Forge", tags: "cobalt-strike,c2,beacon,red-team", version: "2.0" },
  { source: "signature-base", name: "LockBit 3.0 Ransomware Indicators", type: "yara", severity: "critical", mitreTechnique: "T1486", mitreTactic: "Impact", description: "Detects LockBit 3.0 ransomware binary via characteristic strings and encryption patterns", ruleContent: `rule LockBit3_Ransomware {\n  meta:\n    description = "Detects LockBit 3.0 ransomware"\n    author = "Florian Roth"\n    source = "Neo23x0/signature-base"\n    severity = "critical"\n    mitre_technique = "T1486"\n    date = "2023-06-15"\n  strings:\n    $s1 = "LockBit" ascii wide\n    $s2 = "ECDH" ascii\n    $s3 = ".lockbit" ascii wide\n    $s4 = "README.txt" ascii wide fullword\n    $anti1 = { 83 EC 44 53 56 57 FF 15 }\n    $bc1 = "vssadmin delete shadows" ascii wide nocase\n    $bc2 = "wbadmin delete" ascii wide nocase\n  condition:\n    uint16(0) == 0x5A4D and ($s1 or $s3) and 1 of ($bc*)\n}`, author: "Florian Roth (signature-base)", tags: "lockbit,ransomware,impact,critical", version: "1.3" },
  { source: "JPCERT/CC", name: "APT Loader DLL Sideloading", type: "yara", severity: "high", mitreTechnique: "T1574.002", mitreTactic: "Defense Evasion", description: "Detects DLL sideloading patterns used by APT groups — legitimate executable loads malicious DLL", ruleContent: `rule APT_Loader_DLL_Sideloading {\n  meta:\n    description = "Detects DLL sideloading patterns used by APT actors"\n    author = "JPCERT/CC"\n    source = "jpcertcc/jpcert-yara"\n    severity = "high"\n    mitre_technique = "T1574.002"\n    date = "2024-03-01"\n  strings:\n    $mz = { 4D 5A }\n    $exp1 = "DllMain" ascii\n    $anti_analysis1 = "IsDebuggerPresent" ascii\n    $anti_analysis2 = "CheckRemoteDebuggerPresent" ascii\n    $c2_1 = "User-Agent:" ascii\n    $inject1 = "VirtualAllocEx" ascii\n    $inject2 = "WriteProcessMemory" ascii\n    $inject3 = "CreateRemoteThread" ascii\n  condition:\n    $mz at 0 and $exp1 and $anti_analysis1 and\n    ($c2_1 or (2 of ($inject*)))\n}`, author: "JPCERT/CC", tags: "dll-sideloading,apt,defense-evasion", version: "1.0" },
  { source: "YARA-Forge", name: "Sliver C2 Framework", type: "yara", severity: "critical", mitreTechnique: "T1071.001", mitreTactic: "Command and Control", description: "Detects Sliver open-source C2 framework implants — increasingly used by threat actors and red teams", ruleContent: `rule Sliver_C2_Implant {\n  meta:\n    description = "Detects Sliver C2 framework implant"\n    author = "YARA-Forge Contributors"\n    source = "YARAHQ/yara-forge"\n    severity = "critical"\n    mitre_technique = "T1071.001"\n    date = "2024-08-01"\n  strings:\n    $str1 = "github.com/bishopfox/sliver" ascii\n    $str2 = "sliver/implant" ascii\n    $str3 = "SliverClient" ascii\n    $str4 = "implantConfig" ascii\n    $mtls1 = "mtls://" ascii\n    $wg1 = "wireguard" ascii\n  condition:\n    2 of ($str*) or ($mtls1 and $wg1)\n}`, author: "YARA-Forge Contributors", tags: "sliver,c2,post-exploitation", version: "1.2" },
  { source: "signature-base", name: "Webshell PHP Generic", type: "yara", severity: "high", mitreTechnique: "T1505.003", mitreTactic: "Persistence", description: "Detects common PHP webshell patterns — server-side code execution via web interface", ruleContent: `rule Webshell_PHP_Generic {\n  meta:\n    description = "Detects generic PHP webshell patterns"\n    author = "Florian Roth"\n    source = "Neo23x0/signature-base"\n    severity = "high"\n    mitre_technique = "T1505.003"\n    date = "2024-01-10"\n  strings:\n    $php = "<?php" ascii\n    $func1 = "eval(base64_decode(" ascii nocase\n    $func2 = "system($_" ascii\n    $func3 = "exec($_" ascii\n    $func4 = "shell_exec($_" ascii\n    $func5 = "passthru($_" ascii\n    $obf1 = "str_rot13" ascii\n    $obf2 = "gzinflate(base64_decode" ascii\n  condition:\n    $php and (1 of ($func*) or 1 of ($obf*))\n}`, author: "Florian Roth (signature-base)", tags: "webshell,php,persistence,server", version: "3.1" },
  { source: "signature-base", name: "Emotet Downloader", type: "yara", severity: "critical", mitreTechnique: "T1566.001", mitreTactic: "Initial Access", description: "Detects Emotet banking trojan/downloader — one of the most prolific malware loaders", ruleContent: `rule Emotet_Downloader {\n  meta:\n    description = "Detects Emotet malware downloader components"\n    author = "Florian Roth / ANY.RUN"\n    source = "Neo23x0/signature-base"\n    severity = "critical"\n    mitre_technique = "T1566.001"\n    date = "2024-02-01"\n  strings:\n    $s1 = "ITaskService" wide\n    $s2 = "Emotet" ascii nocase\n    $s3 = { 68 ?? ?? ?? ?? 6A 00 6A 00 6A 00 }\n    $eml1 = ".doc" wide\n    $eml2 = "VBA" ascii\n    $net1 = "WinHttpOpen" ascii\n    $net2 = "InternetOpenUrl" ascii\n  condition:\n    uint16(0) == 0x5A4D and (($s1 and $net1) or ($s2) or ($s3 and 1 of ($net*)))\n}`, author: "Florian Roth (signature-base)", tags: "emotet,downloader,banking,initial-access", version: "2.5" },
  { source: "SigmaHQ", name: "DNS Tunneling via Iodine or Dnscat", type: "sigma", severity: "high", mitreTechnique: "T1071.004", mitreTactic: "Command and Control", description: "Detects DNS tunneling tools Iodine and Dnscat2 based on process name and command-line indicators", ruleContent: `title: DNS Tunneling via Iodine or Dnscat\nstatus: stable\nauthor: Tobias Michalski\nlogsource:\n  category: process_creation\n  product: linux\ndetection:\n  selection_iodine:\n    Image|endswith: '/iodine'\n  selection_dnscat:\n    Image|endswith: '/dnscat'\n  selection_cmdline:\n    CommandLine|contains:\n      - '--dns'\n      - '-d '\n      - 'dnscat'\n  condition: 1 of selection_*\nlevel: high\ntags:\n  - attack.command_and_control\n  - attack.t1071.004`, author: "Tobias Michalski (SigmaHQ)", tags: "dns-tunneling,c2,data-exfiltration", version: "1.1" },
  { source: "SigmaHQ", name: "Pass-the-Hash via Sekurlsa", type: "sigma", severity: "critical", mitreTechnique: "T1550.002", mitreTactic: "Lateral Movement", description: "Detects Pass-the-Hash attack using sekurlsa::pth Mimikatz command", ruleContent: `title: Pass-the-Hash via Sekurlsa\nstatus: stable\nauthor: Florian Roth\nlogsource:\n  category: process_creation\n  product: windows\ndetection:\n  selection:\n    CommandLine|contains:\n      - 'sekurlsa::pth'\n      - '/ntlm:'\n      - 'pth-winexe'\n      - 'pth-wmic'\n  condition: selection\nlevel: critical\ntags:\n  - attack.lateral_movement\n  - attack.t1550.002`, author: "Florian Roth (SigmaHQ)", tags: "pass-the-hash,mimikatz,lateral-movement", version: "2.0" },
  { source: "SigmaHQ", name: "Suspicious RDP Session Open", type: "sigma", severity: "medium", mitreTechnique: "T1021.001", mitreTactic: "Lateral Movement", description: "Detects new RDP sessions from unusual source IP ranges or outside business hours", ruleContent: `title: Suspicious RDP Session Opened\nstatus: experimental\nauthor: Samir Bousseaden\nlogsource:\n  product: windows\n  service: security\ndetection:\n  selection:\n    EventID: 4624\n    LogonType: 10\n  filter:\n    IpAddress: '::1'\n  condition: selection and not filter\nlevel: medium\ntags:\n  - attack.lateral_movement\n  - attack.t1021.001`, author: "Samir Bousseaden (SigmaHQ)", tags: "rdp,lateral-movement,remote-access", version: "1.3" },
  { source: "YARA-Forge", name: "AsyncRAT Remote Access Trojan", type: "yara", severity: "high", mitreTechnique: "T1219", mitreTactic: "Command and Control", description: "Detects AsyncRAT — open-source remote access trojan widely distributed via phishing campaigns", ruleContent: `rule AsyncRAT_RAT {\n  meta:\n    description = "Detects AsyncRAT remote access trojan"\n    author = "YARA-Forge / Securonix"\n    source = "YARAHQ/yara-forge"\n    severity = "high"\n    mitre_technique = "T1219"\n    date = "2024-05-15"\n  strings:\n    $s1 = "AsyncRAT" ascii wide nocase\n    $s2 = "Async-RAT" ascii wide nocase\n    $s3 = "127.0.0.1" ascii\n    $s4 = "pastebin.com" ascii\n    $cfg1 = "SERVERIP" ascii\n    $cfg2 = "SERVERPORT" ascii\n    $cfg3 = "MUTEX" ascii\n  condition:\n    2 of ($s*) or (2 of ($cfg*))\n}`, author: "YARA-Forge / Securonix", tags: "asyncrat,rat,c2,remote-access", version: "1.4" },
];

// Simulated update registry — new rules from upstream repos
const UPDATE_REGISTRY = [
  { source: "SigmaHQ", name: "BitLocker Abuse for Ransomware Encryption", type: "sigma", severity: "critical", mitreTechnique: "T1486", version: "1.0", publishedAt: "2025-04-15" },
  { source: "SigmaHQ", name: "AMSI Bypass via Registry Modification", type: "sigma", severity: "high", mitreTechnique: "T1562.001", version: "2.1", publishedAt: "2025-04-18" },
  { source: "YARA-Forge", name: "Brute Ratel C4 Implant Detection", type: "yara", severity: "critical", mitreTechnique: "T1071.001", version: "1.5", publishedAt: "2025-04-22" },
  { source: "signature-base", name: "XWorm RAT v4 Strings", type: "yara", severity: "high", mitreTechnique: "T1219", version: "1.0", publishedAt: "2025-04-29" },
  { source: "SigmaHQ", name: "PowerShell Empire Framework Activity", type: "sigma", severity: "high", mitreTechnique: "T1059.001", version: "3.2", publishedAt: "2025-05-01" },
  { source: "JPCERT/CC", name: "APT10 Cloud Hopper Indicators", type: "sigma", severity: "critical", mitreTechnique: "T1078.004", version: "1.1", publishedAt: "2025-05-02" },
  { source: "JPCERT/CC", name: "OceanLotus Web Shell Indicators", type: "yara", severity: "high", mitreTechnique: "T1505.003", version: "1.0", publishedAt: "2025-05-03" },
];

async function getOrCreateVersion(detectionId: number) {
  const [existing] = await db.select().from(ruleVersionsTable)
    .where(and(eq(ruleVersionsTable.detectionId, detectionId), eq(ruleVersionsTable.isCurrent, true)));
  if (existing) return existing;
  const [detection] = await db.select().from(detectionsTable).where(eq(detectionsTable.id, detectionId));
  if (!detection) return null;
  const [version] = await db.insert(ruleVersionsTable).values({
    detectionId, version: detection.version ?? "1.0", ruleContent: detection.ruleContent,
    stage: detection.status === "active" ? "production" : detection.status === "testing" ? "test" : detection.status === "review" ? "review" : "draft",
    author: detection.author ?? "system", changelog: "Initial version", isCurrent: true,
  }).returning();
  return version;
}

router.get("/rule-pipeline/board", requireAuth, async (req, res) => {
  try {
    const detections = await db.select().from(detectionsTable).orderBy(desc(detectionsTable.updatedAt));
    const result: Record<string, typeof detections> = { draft: [], review: [], test: [], production: [] };
    for (const d of detections) {
      const col = d.status === "active" ? "production" : d.status === "testing" ? "test" : d.status === "review" ? "review" : "draft";
      result[col].push(d);
    }
    res.json(result);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/rule-pipeline/:id/advance", requireAuth, async (req, res) => {
  try {
    const id = Number(req.params.id);
    const [detection] = await db.select().from(detectionsTable).where(eq(detectionsTable.id, id));
    if (!detection) { res.status(404).json({ error: "Detection not found" }); return; }
    const stageMap: Record<string, string> = { disabled: "review", review: "testing", testing: "active", active: "active" };
    const nextStatus = stageMap[detection.status] ?? "review";
    const [updated] = await db.update(detectionsTable).set({ status: nextStatus as any, updatedAt: new Date() }).where(eq(detectionsTable.id, id)).returning();
    const version = await getOrCreateVersion(id);
    if (version) {
      const stageLabel = nextStatus === "active" ? "production" : nextStatus === "testing" ? "test" : "review";
      await db.update(ruleVersionsTable).set({ stage: stageLabel as any }).where(eq(ruleVersionsTable.id, version.id));
    }
    res.json(updated);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.get("/rule-pipeline/:id/versions", requireAuth, async (req, res) => {
  try {
    const versions = await db.select().from(ruleVersionsTable)
      .where(eq(ruleVersionsTable.detectionId, Number(req.params.id)))
      .orderBy(desc(ruleVersionsTable.createdAt));
    res.json(versions);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.post("/rule-pipeline/:id/version", requireAuth, async (req, res) => {
  try {
    const { ruleContent, changelog, author } = req.body;
    const id = Number(req.params.id);
    await db.update(ruleVersionsTable).set({ isCurrent: false }).where(eq(ruleVersionsTable.detectionId, id));
    const [detection] = await db.select().from(detectionsTable).where(eq(detectionsTable.id, id));
    if (!detection) { res.status(404).json({ error: "Detection not found" }); return; }
    const parts = (detection.version ?? "1.0").split(".").map(Number);
    parts[1] = (parts[1] ?? 0) + 1;
    const newVersion = parts.join(".");
    const [v] = await db.insert(ruleVersionsTable).values({ detectionId: id, version: newVersion, ruleContent, stage: "draft", changelog: changelog ?? "Rule updated", author: author ?? "SOC Analyst", isCurrent: true }).returning();
    await db.update(detectionsTable).set({ ruleContent, version: newVersion, status: "disabled", updatedAt: new Date() }).where(eq(detectionsTable.id, id));
    res.status(201).json(v);
  } catch (err) { req.log.error(err); res.status(500).json({ error: "Internal server error" }); }
});

router.get("/rule-pipeline/community", requireAuth, (_req, res) => {
  res.json(COMMUNITY_RULES);
});

router.get("/rule-pipeline/check-updates", requireAuth, (_req, res) => {
  const lastCheck = new Date(Date.now() - 86400000 * 3).toISOString();
  res.json({
    lastChecked: lastCheck,
    available: UPDATE_REGISTRY.length,
    sources: {
      "SigmaHQ": { url: "https://github.com/SigmaHQ/sigma", newRules: UPDATE_REGISTRY.filter(r => r.source === "SigmaHQ").length },
      "YARA-Forge": { url: "https://github.com/YARAHQ/yara-forge", newRules: UPDATE_REGISTRY.filter(r => r.source === "YARA-Forge").length },
      "signature-base": { url: "https://github.com/Neo23x0/signature-base", newRules: UPDATE_REGISTRY.filter(r => r.source === "signature-base").length },
      "JPCERT/CC": { url: "https://github.com/JPCERTCC/jpcert-yara", newRules: UPDATE_REGISTRY.filter(r => r.source === "JPCERT/CC").length },
      "Valhalla": { url: "https://valhalla.nextron-systems.com", newRules: 0 },
      "YARAify": { url: "https://yaraify.abuse.ch", newRules: 0 },
    },
    updates: UPDATE_REGISTRY,
  });
});

export default router;
